### ISSUE TITLE
Airline - Delete

### ISSUE THREAD

**Issue by MichaelSwartz** [MichaelSwartz/airlines#10]
```ruby
As a user
I want to delete an airline
So that no one can review it
```
Acceptance criteria
- I must be on the edit page to see the delete option
- I must be presented with confirmation once airline is deleted

**Comment by MichaelSwartz** [comment]
Update feature test to include confirmation message... could be JS?

**Comment by daverhub** [comment]
Founders decided users should not be able to delete airlines
