### ISSUE TITLE
Admin - Delete Airline

### ISSUE THREAD

**Issue by daverhub** [MichaelSwartz/airlines#24]
As an admin, I want to be able to delete any airline

-- As an admin, I want to navigate to airlines page, and have option to delete airline.

Acceptance Criteria:

- Delete button must be present
- Confirmation must occur
- Flash message will display post delete

**Comment by daverhub** [comment]
Should probably have a pop up!!!

**Comment by MichaelSwartz** [comment]
completed admin delteding airline
