### ISSUE TITLE
Airlines - Create

### ISSUE THREAD

**Issue by MichaelSwartz** [MichaelSwartz/airlines#6]
```ruby
As a user
I want to add an airline
So that others can review it
```
Acceptance criteria
- I must be presented with a form to add airline
- I must be presented with errors if form filled-out incorrectly
- I must be presented with a success message if airline created successfully

**Comment by MichaelSwartz** [comment]
Authentication validations to be built later.
- I must be presented with an error if not signed in

**Comment by daverhub** [comment]
completed user creates airline
